// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using csharp_web.Data;

#nullable disable

namespace csharp_web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220205844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("csharp_web.Models.Burger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.ToTable("burger", (string)null);
                });

            modelBuilder.Entity("csharp_web.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("csharp_web.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etat");

                    b.Property<int?>("LivreurId")
                        .HasColumnType("integer")
                        .HasColumnName("livreur_id");

                    b.Property<int?>("PaiementId")
                        .HasColumnType("integer")
                        .HasColumnName("paiement_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("LivreurId");

                    b.HasIndex("PaiementId");

                    b.HasIndex("ZoneId");

                    b.ToTable("commande", (string)null);
                });

            modelBuilder.Entity("csharp_web.Models.Complement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.ToTable("complement", (string)null);
                });

            modelBuilder.Entity("csharp_web.Models.Gestionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("login");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("gestionnaire", (string)null);
                });

            modelBuilder.Entity("csharp_web.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BurgerId")
                        .HasColumnType("integer")
                        .HasColumnName("burger_id");

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer")
                        .HasColumnName("commande_id");

                    b.Property<int?>("ComplementId")
                        .HasColumnType("integer")
                        .HasColumnName("complement_id");

                    b.Property<int?>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("Id");

                    b.HasIndex("BurgerId");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ComplementId");

                    b.HasIndex("MenuId");

                    b.ToTable("lignecommande", (string)null);
                });

            modelBuilder.Entity("csharp_web.Models.Livreur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("livreur", (string)null);
                });

            modelBuilder.Entity("csharp_web.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("csharp_web.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer")
                        .HasColumnName("commande_id");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Methode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("methode");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric")
                        .HasColumnName("montant");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.ToTable("paiement", (string)null);
                });

            modelBuilder.Entity("csharp_web.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LivreurId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.HasIndex("LivreurId");

                    b.ToTable("zone", (string)null);
                });

            modelBuilder.Entity("csharp_web.Models.Commande", b =>
                {
                    b.HasOne("csharp_web.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("csharp_web.Models.Livreur", "Livreur")
                        .WithMany()
                        .HasForeignKey("LivreurId");

                    b.HasOne("csharp_web.Models.Paiement", "Paiement")
                        .WithMany()
                        .HasForeignKey("PaiementId");

                    b.HasOne("csharp_web.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("Client");

                    b.Navigation("Livreur");

                    b.Navigation("Paiement");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("csharp_web.Models.LigneCommande", b =>
                {
                    b.HasOne("csharp_web.Models.Burger", "Burger")
                        .WithMany()
                        .HasForeignKey("BurgerId");

                    b.HasOne("csharp_web.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("csharp_web.Models.Complement", "Complement")
                        .WithMany()
                        .HasForeignKey("ComplementId");

                    b.HasOne("csharp_web.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId");

                    b.Navigation("Burger");

                    b.Navigation("Commande");

                    b.Navigation("Complement");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("csharp_web.Models.Livreur", b =>
                {
                    b.HasOne("csharp_web.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("csharp_web.Models.Paiement", b =>
                {
                    b.HasOne("csharp_web.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("csharp_web.Models.Zone", b =>
                {
                    b.HasOne("csharp_web.Models.Livreur", null)
                        .WithMany("Zones")
                        .HasForeignKey("LivreurId");
                });

            modelBuilder.Entity("csharp_web.Models.Livreur", b =>
                {
                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
