<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251224202853 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE lignecommande_id_seq CASCADE');
        $this->addSql('CREATE TABLE ligne_commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, commande_id INT NOT NULL, burger_id INT DEFAULT NULL, menu_id INT DEFAULT NULL, complement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3170B74B82EA2E54 ON ligne_commande (commande_id)');
        $this->addSql('CREATE INDEX IDX_3170B74B17CE5090 ON ligne_commande (burger_id)');
        $this->addSql('CREATE INDEX IDX_3170B74BCCD7E912 ON ligne_commande (menu_id)');
        $this->addSql('CREATE INDEX IDX_3170B74B40D9D0AA ON ligne_commande (complement_id)');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74B82EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74B17CE5090 FOREIGN KEY (burger_id) REFERENCES burger (id)');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74BCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id)');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74B40D9D0AA FOREIGN KEY (complement_id) REFERENCES complement (id)');
        $this->addSql('ALTER TABLE lignecommande DROP CONSTRAINT lignecommande_complement_id_fkey');
        $this->addSql('ALTER TABLE lignecommande DROP CONSTRAINT lignecommande_commande_id_fkey');
        $this->addSql('ALTER TABLE lignecommande DROP CONSTRAINT lignecommande_burger_id_fkey');
        $this->addSql('ALTER TABLE lignecommande DROP CONSTRAINT lignecommande_menu_id_fkey');
        $this->addSql('DROP TABLE "__EFMigrationsHistory"');
        $this->addSql('DROP TABLE lignecommande');
        $this->addSql('ALTER TABLE burger ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE burger ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE burger ALTER prix TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE burger ALTER actif DROP DEFAULT');
        $this->addSql('ALTER TABLE burger ALTER actif SET NOT NULL');
        $this->addSql('ALTER TABLE client ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE client ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX client_telephone_key RENAME TO UNIQ_C7440455450FF010');
        $this->addSql('ALTER TABLE commande ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE commande ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE commande ALTER date_commande DROP DEFAULT');
        $this->addSql('ALTER TABLE commande ALTER date_commande SET NOT NULL');
        $this->addSql('ALTER TABLE complement ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE complement ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE complement ALTER prix TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE complement ALTER actif DROP DEFAULT');
        $this->addSql('ALTER TABLE complement ALTER actif SET NOT NULL');
        $this->addSql('ALTER TABLE gestionnaire ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE gestionnaire ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE gestionnaire ALTER telephone SET NOT NULL');
        $this->addSql('ALTER TABLE gestionnaire ALTER login TYPE VARCHAR(180)');
        $this->addSql('ALTER INDEX gestionnaire_login_key RENAME TO UNIQ_F4461B20AA08CB10');
        $this->addSql('ALTER TABLE livreur ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE livreur ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE menu ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE menu ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE menu ALTER actif DROP DEFAULT');
        $this->addSql('ALTER TABLE menu ALTER actif SET NOT NULL');
        $this->addSql('ALTER TABLE paiement ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE paiement ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE paiement ALTER date_paiement DROP DEFAULT');
        $this->addSql('ALTER TABLE paiement ALTER date_paiement SET NOT NULL');
        $this->addSql('ALTER TABLE paiement ALTER montant TYPE DOUBLE PRECISION');
        $this->addSql('ALTER INDEX paiement_commande_id_key RENAME TO UNIQ_B1DC7A1E82EA2E54');
        $this->addSql('ALTER TABLE zone ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE zone ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE zone ALTER prix TYPE DOUBLE PRECISION');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE lignecommande_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE "__EFMigrationsHistory" ("MigrationId" VARCHAR(150) NOT NULL, "ProductVersion" VARCHAR(32) NOT NULL, PRIMARY KEY ("MigrationId"))');
        $this->addSql('CREATE TABLE lignecommande (id INT DEFAULT nextval(\'lignecommande_id_seq\'::regclass) NOT NULL, commande_id INT NOT NULL, burger_id INT DEFAULT NULL, menu_id INT DEFAULT NULL, complement_id INT DEFAULT NULL, quantite INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_853B793940D9D0AA ON lignecommande (complement_id)');
        $this->addSql('CREATE INDEX IDX_853B793982EA2E54 ON lignecommande (commande_id)');
        $this->addSql('CREATE INDEX IDX_853B793917CE5090 ON lignecommande (burger_id)');
        $this->addSql('CREATE INDEX IDX_853B7939CCD7E912 ON lignecommande (menu_id)');
        $this->addSql('ALTER TABLE lignecommande ADD CONSTRAINT lignecommande_complement_id_fkey FOREIGN KEY (complement_id) REFERENCES complement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lignecommande ADD CONSTRAINT lignecommande_commande_id_fkey FOREIGN KEY (commande_id) REFERENCES commande (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lignecommande ADD CONSTRAINT lignecommande_burger_id_fkey FOREIGN KEY (burger_id) REFERENCES burger (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lignecommande ADD CONSTRAINT lignecommande_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74B82EA2E54');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74B17CE5090');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74BCCD7E912');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74B40D9D0AA');
        $this->addSql('DROP TABLE ligne_commande');
        $this->addSql('ALTER TABLE burger ALTER id SET DEFAULT nextval(\'burger_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE burger ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE burger ALTER prix TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE burger ALTER actif SET DEFAULT true');
        $this->addSql('ALTER TABLE burger ALTER actif DROP NOT NULL');
        $this->addSql('ALTER TABLE client ALTER id SET DEFAULT nextval(\'client_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE client ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_c7440455450ff010 RENAME TO client_telephone_key');
        $this->addSql('ALTER TABLE commande ALTER id SET DEFAULT nextval(\'commande_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE commande ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE commande ALTER date_commande SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE commande ALTER date_commande DROP NOT NULL');
        $this->addSql('ALTER TABLE complement ALTER id SET DEFAULT nextval(\'complement_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE complement ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE complement ALTER prix TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE complement ALTER actif SET DEFAULT true');
        $this->addSql('ALTER TABLE complement ALTER actif DROP NOT NULL');
        $this->addSql('ALTER TABLE gestionnaire ALTER id SET DEFAULT nextval(\'gestionnaire_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE gestionnaire ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE gestionnaire ALTER telephone DROP NOT NULL');
        $this->addSql('ALTER TABLE gestionnaire ALTER login TYPE VARCHAR(255)');
        $this->addSql('ALTER INDEX uniq_f4461b20aa08cb10 RENAME TO gestionnaire_login_key');
        $this->addSql('ALTER TABLE livreur ALTER id SET DEFAULT nextval(\'livreur_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE livreur ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE menu ALTER id SET DEFAULT nextval(\'menu_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE menu ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE menu ALTER actif SET DEFAULT true');
        $this->addSql('ALTER TABLE menu ALTER actif DROP NOT NULL');
        $this->addSql('ALTER TABLE paiement ALTER id SET DEFAULT nextval(\'paiement_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE paiement ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE paiement ALTER date_paiement SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE paiement ALTER date_paiement DROP NOT NULL');
        $this->addSql('ALTER TABLE paiement ALTER montant TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER INDEX uniq_b1dc7a1e82ea2e54 RENAME TO paiement_commande_id_key');
        $this->addSql('ALTER TABLE zone ALTER id SET DEFAULT nextval(\'zone_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE zone ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE zone ALTER prix TYPE NUMERIC(10, 2)');
    }
}
